Change division style to prevent error in python3
Using python2 style '/' will convert int type to float in python3 which will cause the following error when creating FloatTensor:

TypeError: torch.FloatTensor constructor received an invalid combination of arguments - got (float, int, int, int), but expected one of:
 * no arguments
 * (int ...)
      didn't match because some of the arguments have invalid types: (float, int, int, int)