Fix division in normalization
RuntimeError: Integer division of tensors using div or / is no longer supported, and in a future release div will perform true division as in Python 3.