Back out "[fbcode] Reduce log spam from torchvision video reader"
Summary:
Original commit changeset: a808210c1dda

Original Phabricator Diff: D53062741

Unfortunately I have to backout D53062741 as it is not compiling properly on the torchvision GitHub repo (source of truth): This [this PR](https://github.com/pytorch/vision/pull/8333)  which includes the changes from D53062741 but fails with

```
  /pytorch/vision/torchvision/csrc/io/video_reader/video_reader.cpp:477:17: error: ‘ERROR’ was not declared in this scope; did you mean ‘AVERROR’?
    477 |     LOG_EVERY_N(ERROR, 1000) << "Decoder initialization has failed";
        |                 ^~~~~
  Traceback (most recent call last):
    File "/home/ec2-user/actions-runner/_work/vision/vision/test-infra/.github/scripts/run_with_env_secrets.py", line 101, in <module>
      main()
    File "/home/ec2-user/actions-runner/_work/vision/vision/test-infra/.github/scripts/run_with_env_secrets.py", line 97, in main
      run_cmd_or_die(f"docker exec -t {container_name} /exec")
    File "/home/ec2-user/actions-runner/_work/vision/vision/test-infra/.github/scripts/run_with_env_secrets.py", line 38, in run_cmd_or_die
      raise RuntimeError(f"Command {cmd} failed with exit code {exit_code}")
  RuntimeError: Command docker exec -t f02046f9ef9ce5646ae4a84fe51204d4594ecbcbcc66e4572c681290939d87c4 /exec failed with exit code 1
        |                 AVERROR
  /pytorch/vision/torchvision/csrc/io/video_reader/video_reader.cpp:477:5: error: ‘LOG_EVERY_N’ was not declared in this scope; did you mean ‘C10_LOG_EVERY_N’?
    477 |     LOG_EVERY_N(ERROR, 1000) << "Decoder initialization has failed";
        |     ^~~~~~~~~~~
        |     C10_LOG_EVERY_N
  /pytorch/vision/torchvision/csrc/io/video_reader/video_reader.cpp:510:17: error: ‘ERROR’ was not declared in this scope; did you mean ‘AVERROR’?
    510 |     LOG_EVERY_N(ERROR, 1000) << "Miss video stream";
        |                 ^~~~~
        |                 AVERROR
  /pytorch/vision/torchvision/csrc/io/video_reader/video_reader.cpp:510:5: error: ‘LOG_EVERY_N’ was not declared in this scope; did you mean ‘C10_LOG_EVERY_N’?
    510 |     LOG_EVERY_N(ERROR, 1000) << "Miss video stream";
        |     ^~~~~~~~~~~
        |     C10_LOG_EVERY_N
```

It seems that `LOG_EVERY_N` is only present internally on fbcode because of some internal transitive dependency.

Reviewed By: vmoens

Differential Revision: D58283929

fbshipit-source-id: ac5f2f389b8b12ed019cb5aaa8b331e7c89a9acd