[torchvision] replace if statement with assert for TRT compilation
Summary:
Trying to use trt + deform_conv2d
```
return torchvision.ops.deform_conv2d(
            x,
            offset,
            self.weight,
            self.bias,
            self.stride,
            self.padding,
            self.dilation,
            mask,
        )
```
cause an error

```
torch.fx.proxy.TraceError: symbolically traced variables cannot be used as inputs to control flow
 File "/mnt/xarfuse/uid-29409/e2de88e3-seed-nspid4026534060_cgpid13798698-ns-4026534057/torchvision/ops/deform_conv.py", line 85, in deform_conv2d
    if n_offset_grps == 0:
```

Differential Revision: D46070158

fbshipit-source-id: e3ccd662d7476337c31eacfd0662a609eb2776eb